

GET http://localhost:3000/todos/?category=WORK&status=DONE
###

GET http://localhost:3000/todos/6/
###

GET http://localhost:3000/agenda/?date=2021-1-12
###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
###
DELETE http://localhost:3000/todos/6/
###


PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
      "priority": "HIGH"
}